export '../comment/screens/commentScreen.dart';
// export 'create_journalScreen.dart';
// export 'createPostScreen.dart';
// export 'editProfileScreen.dart';
export '../user/screens/othersProfileScreen.dart';
export '../user/screens/followerScreen.dart';
export '../user/screens/editProfileScreen.dart';
export '../user/screens/followingScreen.dart';
export '../custom/journal_card.dart';
export 'loginScreen.dart';
export '../custom/postCard.dart';
// export 'profileScreen.dart';
// export 'searchScreen.dart';
export 'signupScreen.dart';
// export 'postListScreen.dart';
export 'homeScreen.dart';
// export 'editPendingPostScreen.dart';
export '../journal/screens/editPendingJournalScreen.dart';
// export 'journalListScreen.dart';
// export 'pendingPostListScreen.dart';
// export 'pendingJournalListScreen.dart';
export '../user/screens/othersFollowerScreen.dart';
